version: "3.8"
services:
  app:
    build: .
    image: ainayves/cgpt
    volumes:
      - ./data:/home/app_user/data
    stdin_open: true
    tty: true
    user: root
    command: /bin/bash -c "chmod +x ./build.sh && ./build.sh && cgpt"